apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: ingress-manager-rb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-manager-role
subjects:
- kind: ServiceAccount
  name: ingress-manager-sa
  namespace: default
